---
# To get started with Dependabot version updates, you"ll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: "gradle"
    target-branch: "main"
    directory: "/backend"
    labels:
      - "dependabot"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      gradle-version-updates-minor-patch:
        applies-to: "version-updates"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/frontend"
    labels:
      - "dependabot"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      npm-version-updates-minor-patch:
        applies-to: "version-updates"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "dependabot"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directory: "/"
    labels:
      - "dependabot"
    schedule:
      interval: "monthly"