export enum Role {
    NONE = 'ROLE_NONE',
    ADMIN = 'ROLE_ADMIN',
    EVENT_PLANNER = 'ROLE_EVENT_PLANNER',
    EVENT_LEADER = 'ROLE_EVENT_LEADER',
    TEAM_PLANNER = 'ROLE_TEAM_PLANNER',
    TEAM_MEMBER = 'ROLE_TEAM_MEMBER',
    USER_MANAGER = 'ROLE_USER_MANAGER',
}
