# https://docs.spring.io/spring-boot/appendix/application-properties/index.html

build:
  time: ${BUILD_DATE:now}
  commit: ${BUILD_COMMIT:local}
  branch: ${BUILD_BRANCH:main}

email:
  host: ${EMAIL_HOST:}
  port: ${EMAIL_PORT:587}
  protocol: ${EMAIL_PROTOCOL:smtp}
  username: ${EMAIL_USERNAME:}
  password: ${EMAIL_PASSWORD:}
  starttls: ${EMAIL_START_TLS:true}

auth:
  logout-success-url: ${frontend.domain}/login
  login-success-url: ${frontend.domain}
  admins: ${ADMIN_EMAILS:}
  # 60 * 60 * 24 * 30 seconds
  session-timout: 2592000

security:
  # TODO csrf protection currently blocks all post requests even if the xsrf token is present
  # temporary disabled until further investigation
  enable-csrf: false

data:
  directory: ${DATA_DIRECTORY:data}
  encryption-password: ${DATA_ENCRYPTION_PASSWORD:default-encryption-password}
  db-url: jdbc:sqlite:${data.directory}/eventplanner.db
  generate-test-data: false
  import:
    users-excel-password: ${USERS_EXCEL_PASSWORD:}
    directory: ${DATA_IMPORT_DIRECTORY:${data.directory}/import}

spring:
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    url: ${data.db-url}
  security:
    oauth2:
      client:
        registration:
          default:
            client-id: ${OAUTH_CLIENT_ID:eventplanner}
            client-secret: ${OAUTH_CLIENT_SECRET:********************}
            provider: default
            redirect-uri: ${frontend.domain}/login/oauth2/code/default
            scope: openid,email,profile
          cognito:
            client-id: ${OAUTH_CLIENT_ID:eventplanner}
            client-secret: ${OAUTH_CLIENT_SECRET:********************}
            provider: default
            redirect-uri: ${frontend.domain}/login/oauth2/code/cognito
            scope: openid,email,profile
        provider:
          default:
            issuer-uri: ${OAUTH_ISSUER_URI:https://cognito-idp.eu-central-1.amazonaws.com/eu-central-1_erXnjLJc7}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  session:
    timeout: ${auth.session-timout}

server:
  protocol: ${SERVER_PROTOCOL:http}
  host: ${SERVER_HOST:localhost}
  port: ${SERVER_PORT:8080}
  domain: ${SERVER_URI:${server.protocol}://${server.host}:${server.port}}
  servlet:
    session:
      timeout: ${auth.session-timout}s
      cookie:
        max-age: ${auth.session-timout}

frontend:
  protocol: ${server.protocol}
  host: ${server.host}
  port: ${server.port}
  domain: ${frontend.protocol}://${frontend.host}:${frontend.port}
