# https://docs.spring.io/spring-boot/appendix/application-properties/index.html

build:
  time: ${BUILD_DATE:now}
  commit: ${BUILD_COMMIT:local}
  branch: ${BUILD_BRANCH:main}

email:
  from: ${EMAIL_FROM:}
  from-display-name: ${EMAIL_FROM_DISPLAY_NAME:}
  reply-to: ${EMAIL_REPLY_TO:}
  reply-to-display-name: ${EMAIL_REPLY_TO_DISPLAY_NAME:}
  host: ${EMAIL_HOST:}
  port: ${EMAIL_PORT:587}
  protocol: ${EMAIL_PROTOCOL:smtp}
  username: ${EMAIL_USERNAME:}
  password: ${EMAIL_PASSWORD:}
  enable-starttls: ${EMAIL_ENABLE_START_TLS:true}
  enable-ssl: ${EMAIL_ENABLE_SSL:false}
  footer: ${EMAIL_FOOTER:}
  # If not empty email notifications will only be sent to these email addresses
  recipients-whitelist: ${EMAIL_WHITELIST:}

auth:
  logout-success-url: ${frontend.url}/login
  login-success-url: ${frontend.url}
  # OIDC users with this email address in their token will automatically become admins
  admins: ${ADMIN_EMAILS:}
  # 60 * 60 * 24 * 30 seconds
  session-timout: 2592000

security:
  # TODO csrf protection currently blocks all post requests even if the xsrf token is present
  # temporary disabled until further investigation
  enable-csrf: false

data:
  directory: ${DATA_DIRECTORY:data}
  encryption-password: ${DATA_ENCRYPTION_PASSWORD:default-encryption-password}
  db-url: jdbc:sqlite:${data.directory}/eventplanner.db
  generate-test-data: false
  import:
    users-excel-password: ${USERS_EXCEL_PASSWORD:}
    directory: ${DATA_IMPORT_DIRECTORY:${data.directory}/import}

spring:
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    url: ${data.db-url}
  security:
    oauth2:
      client:
        registration:
          default:
            client-id: ${OAUTH_CLIENT_ID:eventplanner}
            client-secret: ${OAUTH_CLIENT_SECRET:********************}
            provider: default
            redirect-uri: ${frontend.url}/login/oauth2/code/default
            scope: openid,email,profile
        provider:
          default:
            issuer-uri: ${OAUTH_ISSUER_URI}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  session:
    timeout: ${auth.session-timout}

server:
  protocol: ${PROTOCOL:http}
  host: ${HOST:localhost}
  port: ${PORT:80}
  url: ${HOST_URL:${server.protocol}://${server.host}:${server.port}}
  servlet:
    session:
      timeout: ${auth.session-timout}s
      cookie:
        max-age: ${auth.session-timout}

frontend:
  protocol: ${server.protocol}
  host: ${server.host}
  port: ${server.port}
  url: ${HOST_URL:${frontend.protocol}://${frontend.host}:${frontend.port}}

logging:
  file:
    path:
      ./logs
