server:
  port: ${SERVER_PORT:80}
  host: ${SERVER_HOST:}
  protocol: https
  domain: https://${server.host}

frontend:
  port: 80
  host: ${server.host}
  protocol: https
  domain: https://${frontend.host}



