# ---------------------------
# Configuration for local development. Copy this file to application-local.yml
# and adjust the environment variables to your needs. Then run the app with
# MODE=local to use this profile.
# ---------------------------

# OIDC configuration used to login to the application. This can be anny OAuth2
# issuer, e.g. Keycloak, Auth0, Okta, AWS Cognito etc.
OAUTH_ISSUER_URI: https://example.com/realms/myrealm
OAUTH_CLIENT_ID: eventplanner
OAUTH_CLIENT_SECRET: '******************'

# By default, the application will boot up using a SQLite database. If you want
# to use a PostgreSQL database instead, set the following environment variables.
# DATABASE_URL: 'postgres://localhost:5432/eventplanner'
# DATABASE_USERNAME: admin
# DATABASE_PASSWORD: admin

# The secret used to encrypt personal data in the database.
DATA_ENCRYPTION_PASSWORD: super-secret-password

# The secret used to hash access keys.
ACCESS_KEY_HASH_SECRET: super-secret-access-key-secret

# Send email notifications only to whitelisted emails. You can specify multiple
# email addresses in a comma separated list.
EMAIL_WHITELIST: example@email.com

# Add a prefix to emails send from this environment, e.g. to differentiate test
# emails from production emails.
EMAIL_PREFIX: '[TEST] '

# OIDC users with this email address in their token will automatically become
# admins. It is recommended to use this only to set up a first admin user, and
# then remove this configuration again. You can specify multiple email addresses
# in a comma separated list.
ADMIN_EMAILS: example@email.com

# Default log level for the application.
LOG_LEVEL: DEBUG

backend:
  protocol: http
  host: localhost
  port: 8081

frontend:
  protocol: http
  host: localhost
  port: 8080

server:
  servlet:
    session:
      cookie:
        same-site: lax # lax required because frontend and backend run on different ports
        secure: false
