package org.eventplanner.architecture;

import java.lang.annotation.Annotation;
import java.lang.reflect.AnnotatedArrayType;
import java.lang.reflect.AnnotatedType;
import java.lang.reflect.Parameter;
import java.util.Arrays;
import java.util.List;

import org.jspecify.annotations.NonNull;
import org.jspecify.annotations.Nullable;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;

import com.tngtech.archunit.base.DescribedPredicate;
import com.tngtech.archunit.core.domain.JavaClass;
import com.tngtech.archunit.core.domain.JavaCodeUnit;
import com.tngtech.archunit.core.domain.JavaConstructor;
import com.tngtech.archunit.core.domain.JavaMethod;
import com.tngtech.archunit.lang.ArchCondition;
import com.tngtech.archunit.lang.ConditionEvent;
import com.tngtech.archunit.lang.ConditionEvents;
import com.tngtech.archunit.lang.SimpleConditionEvent;

public class ArchUnitHelpers {

    public static DescribedPredicate<JavaClass> isPrimitive() {
        return new DescribedPredicate<>("that is a primitive") {
            @Override
            public boolean test(final JavaClass clazz) {
                return clazz.isPrimitive();
            }
        };
    }

    public static DescribedPredicate<JavaCodeUnit> areNotLombokGenerated() {
        return new DescribedPredicate<>("are not generated by lombok") {
            @Override
            public boolean test(final JavaCodeUnit unit) {
                return unit.tryGetAnnotationOfType("lombok.Generated").isEmpty();
            }
        };
    }

    public static DescribedPredicate<JavaCodeUnit> areNotRecordOrEnumFunctions() {
        return new DescribedPredicate<>("are not record functions") {
            @Override
            public boolean test(final JavaCodeUnit unit) {
                if (unit.getOwner().isRecord()) {
                    return !List.of("equals", "toString").contains(unit.getName());
                }
                if (unit.getOwner().isEnum()) {
                    return !List.of("values", "$values", "toString", "valueOf").contains(unit.getName());
                }
                return true;
            }
        };
    }

    public static DescribedPredicate<JavaCodeUnit> areNotDeclaredInEnums() {
        return new DescribedPredicate<>("are not declare in enums") {
            @Override
            public boolean test(final JavaCodeUnit unit) {
                return !unit.getOwner().isEnum();
            }
        };
    }

    public static ArchCondition<JavaMethod> haveNullMarkedReturnType() {
        return new ArchCondition<>("have null marked return type") {
            @Override
            public void check(JavaMethod method, ConditionEvents events) {
                var returnType = method.reflect().getAnnotatedReturnType();
                if (isNullMarked(returnType)) {
                    var message = ConditionEvent.createMessage(method, "return type is null marked");
                    events.add(new SimpleConditionEvent(method, true, message));
                } else {
                    var message = ConditionEvent.createMessage(method, "return type is not null marked");
                    events.add(new SimpleConditionEvent(method, false, message));
                }
            }
        };
    }

    public static ArchCondition<JavaConstructor> haveAllConstructorParametersNullMarked() {
        return new ArchCondition<>("have all parameters null marked") {
            @Override
            public void check(JavaConstructor constructor, ConditionEvents events) {
                var parameters = constructor.reflect().getAnnotatedParameterTypes();
                for (final AnnotatedType parameter : parameters) {
                    if (isNullMarked(parameter)) {
                        var message = ConditionEvent.createMessage(constructor, "parameter type is null marked");
                        events.add(new SimpleConditionEvent(constructor, true, message));
                    } else {
                        var message = ConditionEvent.createMessage(constructor, "parameter type is not null marked");
                        events.add(new SimpleConditionEvent(constructor, false, message));
                    }
                }
            }
        };
    }

    public static ArchCondition<JavaMethod> haveAllMethodParametersNullMarked() {
        return new ArchCondition<>("have all parameters null marked") {
            @Override
            public void check(JavaMethod method, ConditionEvents events) {
                var parameters = method.reflect().getAnnotatedParameterTypes();
                for (final AnnotatedType parameter : parameters) {
                    if (isNullMarked(parameter)) {
                        var message = ConditionEvent.createMessage(method, "parameter type is null marked");
                        events.add(new SimpleConditionEvent(method, true, message));
                    } else {
                        var message = ConditionEvent.createMessage(method, "parameter type is not null marked");
                        events.add(new SimpleConditionEvent(method, false, message));
                    }
                }
            }
        };
    }

    public static void checkParametersAreNullMarked(
        JavaCodeUnit unit, Parameter[] parameters, Annotation[][] annotations, ConditionEvents events) {
        var anyViolation = false;
        for (int i = 0; i < parameters.length; i++) {
            var parameter = parameters[i];
            var annotationClasses = Arrays.stream(annotations[i])
                .map(Annotation::annotationType)
                .toList();
            if (!parameter.getName().equals("$enum$name")
                && !parameter.getType().isPrimitive()
                && !annotationClasses.contains(Value.class)
                && !annotationClasses.contains(Autowired.class)
                && !annotationClasses.contains(NonNull.class)
                && !annotationClasses.contains(Nullable.class)) {
                anyViolation = true;
                var message =
                    ConditionEvent.createMessage(unit, "parameter " + parameter.getName() + " is not null marked");
                events.add(new SimpleConditionEvent(unit, false, message));
            }
        }
        if (!anyViolation) {
            var message = ConditionEvent.createMessage(unit, "All parameters are null marked");
            events.add(new SimpleConditionEvent(unit, true, message));
        }
    }

    public static boolean isNullMarked(AnnotatedType type) {
        var returnTypeAnnotations = type.getAnnotations();
        if (type instanceof AnnotatedArrayType annotatedArrayType) {
            returnTypeAnnotations = annotatedArrayType.getAnnotatedGenericComponentType().getAnnotations();
        }
        if (type.getType() instanceof Class<?> clazz && clazz.isPrimitive()) {
            return true;
        }
        return Arrays.stream(returnTypeAnnotations)
            .anyMatch(annotation -> annotation.annotationType().getSimpleName().equals("NonNull")
                || annotation.annotationType().getSimpleName().equals("Nullable"));
    }
}
