name: Backend

on:
  pull_request:
    branches:
    - main
    types:
    - opened
    - reopened
    - synchronize
    paths:
    - 'backend/build.gradle'
    - 'backend/settings.gradle'
    - 'backend/src/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: temurin

    - name: Set up test db
      shell: bash
      working-directory: backend
      run: |
        mkdir data
        cp src/test/resources/eventplanner-test.db data/eventplanner-test.db

    - name: Check tests
      shell: bash
      working-directory: backend
      run: ./gradlew test

    - name: Check build
      shell: bash
      working-directory: backend
      run: ./gradlew build

    - name: Store reports
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: |
          **/build/reports/
          **/build/test-results
