name: Build and push Docker container

on:
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:


jobs:
  build-and-push-container:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'true'
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      # Set up BuildKit Docker container builder to be able to build
      # multi-platform images and export cache
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into ghcr registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into private aws registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ vars.AWS_ECR_REPOSITORY }}
          username: ${{ secrets.AWS_ACCESS_KEY }}
          password: ${{ secrets.AWS_ACCESS_SECRET }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date '+%Y-%m-%d %H:%M:%S')"
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5.0.0
        with:
          context: .
          build-args: |
            COMMIT=${{ github.sha }}
            BRANCH=${{ github.head_ref }}
            TIME=${{ steps.date.outputs.date }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/grossherzogin-elisabeth/eventplanner:latest
            ghcr.io/grossherzogin-elisabeth/eventplanner:1.0.0-alpha
            ${{ vars.AWS_ECR_REPOSITORY }}/eventplanner:latest
            ${{ vars.AWS_ECR_REPOSITORY }}/eventplanner:1.0.0-alpha
          cache-from: type=gha
          cache-to: type=gha,mode=max
