name: Frontend

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - 'frontend/**'
jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Node
        uses: actions/setup-node@v5
        with:
          node-version: 22.8.0

      - name: Install dependencies
        shell: bash
        working-directory: frontend
        run: npm ci

      - name: Check format
        shell: bash
        working-directory: frontend
        run: npm run check:format

      - name: Check eslint
        shell: bash
        working-directory: frontend
        run: npm run check:lint

      - name: Check build
        shell: bash
        working-directory: frontend
        run: npm run build
